### ISSUE TITLE
自動的にNSFWコンテンツを検知し、処理するためにNSFW.jsを実装する

### ISSUE THREAD

**Issue by L4Ph** [aipictors/aipictors#107]
# What
NSFW.jsの実装

- [x] クライアント側に実装するか、サーバー側に実装するかを考える
- [ ] [NSFW.js](https://github.com/infinitered/nsfwjs)の実装
- [x] [nsfw_model](https://github.com/gantman/nsfw_model)の配置
- [ ] [nsfw_model](https://github.com/gantman/nsfw_model)の追加学習

## 参考 
- https://github.com/misskey-dev/misskey/pull/8840
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8739

# Why

だいたい参考URL先に書いてあるけど、

> - ユーザーの利便性向上のため
> - モデレーション効率向上のため
> - 犯罪抑止のため

**Comment by Katsuyuki-Karasawa** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-nsfw-censor
https://huggingface.co/CompVis/stable-diffusion-safety-checker

**Comment by Katsuyuki-Karasawa** [comment]
クライアント側でいい気がしてる

**Comment by Katsuyuki-Karasawa** [comment]
https://github.com/alex000kim/nsfw_data_scraper

**Comment by Katsuyuki-Karasawa** [comment]
@nakatsuka-k 意見が欲しい

**Comment by mikageymir** [comment]
精度を見てみたいです。

このような画像タグがあるときに

`<img class="operator-image" src="https://www.aipictors.com/wp-content/uploads/2024/01/xxxx.webp" style="width: 100%; height: auto;" onload="resizeListImg('works_123456789'); return false;">`

特定の関数呼ぶと、 .operator-image についてNSFW.jsで判定して、data-agelimit="0"～"3"のattrを設定してくれる。
（0:全年齢、1:R18、2:R18G、3:R15）
みたいなJavaScriptのコードサンプルがあったらこちらで組み込んで使ってみます。

ある程度の精度があるなら、まずは投稿時にNSFW.jsの結果に応じて年齢区分のデフォルトを変えるだけでも効果がありそうです。

**Comment by Katsuyuki-Karasawa** [comment]
軽くNSFW.jsで検証した感じ、MobileNetだとちょっと無理がありそう
InceptionNetはかなりちゃんと検出する

**Comment by nakatsuka-k** [comment]
検証ありがとうございます。

**Comment by L4Ph** [comment]
https://huggingface.co/datasets/deepghs/nsfw_detect/tree/main

Inception V3はデカいので、小さくするためにMobileNet v3に差し替えて、データセットも比較的新しいものを使う(train用のコードがだいぶ古くていろいろ動かないので、直す必要がある)

**Comment by L4Ph** [comment]
https://huggingface.co/deepghs/imgutils-models/tree/main/nsfw
ONNX用のモデルを見つけた

Hug space
https://huggingface.co/spaces/deepghs/nsfw_prediction

**Comment by L4Ph** [comment]
ONNX Web Runtimeで動かせそう
https://github.com/microsoft/onnxruntime/tree/main/js/web

**Comment by nakatsuka-k** [comment]
こちら、センシティブと全年齢でURL分けたことと、R15の誤判定がこわいのでCloseします。
