### ISSUE TITLE
ネガティブプロンプトを空にすることができない

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [aipictors/aipictors#296]
https://github.com/aipictors/aipictors/assets/70247011/babb5b0c-ff18-49d1-93c8-cba9e61b2210

**Comment by Katsuyuki-Karasawa** [comment]
一応仕様らしい
空けておいて、そのうちベストプラクティス模索する

**Comment by nakatsuka-k** [comment]
空にできるようにしておきました。
