### ISSUE TITLE
ローカルストレージの値を使用してる全てのコンポーネントで発生しうるエラーを直す

### ISSUE THREAD

**Issue by nakatsuka-k** [aipictors/aipictors#333]
Using browser-only APIs like window or localStorage in your rendering logic
https://nextjs.org/docs/messages/react-hydration-error
[Text content does not match server-rendered HTML](https://nextjs.org/docs/messages/react-hydration-error)

擬似ローディングを実装してレンダリングを遅延させて、Node.jsとブラウザの
どっちでもローディングのコンポーネントを表示すれば解決する。
それか、コンポーネントを動的にImportして遅延させる。

**Comment by reiwa** [comment]
Viewに該当する層の関数は全てDynamicにしてもいいかもしれん。

![Screenshot 2024-03-17 at 17 07 26](https://github.com/aipictors/aipictors/assets/8127869/25557c15-2ba9-455b-a68a-579d76051b7a)
