### ISSUE TITLE
画像の取得に失敗する

### ISSUE THREAD

**Issue by reiwa** [aipictors/aipictors#372]
## どの機能に関する不具合ですか？

- [x] 画像生成
- [ ] モデル
- [ ] LoRA
- [ ] プロンプト
- [ ] 生成履歴
- [ ] それ以外

## どのような不具合が発生しましたか？

画像の取得に失敗した際にErrorBoundaryが拾う必要がある。

![Screenshot 2024-03-26 at 3 03 36](https://github.com/aipictors/aipictors/assets/8127869/05777b55-2ba6-4858-834c-6e39d661020e)

## どのような操作をしましたか？

1. xxx
1. xxx
1. xxx

## どの端末で確認しましたか？

- [ ] iOS
- [ ] Android

## 許せないですか？

- [ ] 許せる
- [x] 許せない

**Comment by nakatsuka-k** [comment]
生成画像（private image）を直接リンクで取得するようになったのでFetchエラーになることが無くなり解決済み
