### ISSUE TITLE
画面サイズを最小にした時ログインボタンが見切れる

### ISSUE THREAD

**Issue by ebibibibibi** [aipictors/aipictors#374]
## どの機能に関する不具合ですか？

- [ ] 決済
- [ ] ログイン
- [ ] 投稿
- [ ] いいね
- [ ] リクエスト
- [ ] 多言語
- [ ] フィード
- [ ] お知らせ
- [ ] お問い合わせ
- [x] それ以外

## どのような不具合が発生しましたか？

Discode経由で Aipictorsの生成リンクを Arcで開き、画面サイズを最小にしたとき、ログインボタンUIに見切れが発生する

![image](https://github.com/aipictors/aipictors/assets/91860481/3742aa32-ffaa-4bb5-baa5-3ed178ee54a7)

## どのような操作をしましたか？

1. Discodeを立ち上げる
2. Aipictorsにログインしていない状態で下記リンクを踏み、Arcで開く
https://beta.aipictors.com/generation
3. 画面サイズを最小にする

## どの端末で確認しましたか？

- [x] macBook 
なお、Safari・Braveをデフォルトブラウザに設定している際は同一の手順を踏んでも再現しない。

## 許せないですか？

- [ ] 許せる
- [x] 許せない

**Comment by reiwa** [comment]
許せない。

![Screenshot 2024-03-27 at 4 51 22](https://github.com/aipictors/aipictors/assets/8127869/7732462c-9fbb-41e5-8d26-b515cb4c8c5a)
