### ISSUE TITLE
リダイレクト用のパスを追加する

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#543]
## どのような問題がありますか？

リダイレクトの為のファイルが増えてきてる。今後も増える。

## どうすれば良いですか？

このようなパスを追加してIF分でリダイレクトできる。

- routes
  - $.ts

**Comment by nakatsuka-k** [comment]
わかった。

**Comment by nakatsuka-k** [comment]
リダイレクトの処理をまとめた
https://github.com/aipictors/aipictors/pull/755
