### ISSUE TITLE
($lang)._main.$user.albums.$albumは機能しない

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#673]
機能しないのでURLを変更する必要がある。

```
($lang)._main.$user.albums.$album
```

この場合は$langと$userの2つが変数になるのでユーザ「en」と言語「en」が衝突する。

```
/en/albums/a
```

正しくは

```
($lang)._main.albums.$album
```

**Comment by nakatsuka-k** [comment]
現状は不要なルーティングだったため、削除した。
必要になったら追加する。

**Comment by nakatsuka-k** [comment]
https://github.com/aipictors/aipictors/commit/f271b91090a353523fba6aea96399d8a6e72f702

**Comment by nakatsuka-k** [comment]
ユーザがアルバム名のスラッグ名を任意に命名できる仕様になっている
https://beta.aipictors.com/admin/albums/test

@shigurenimo 
ユーザIDに、enの使用を禁止しようと思った

**Comment by nakatsuka-k** [comment]
ユーザIDに `en` で更新できないようにした

**Comment by shigurenimo** [comment]
これは機能しない。先に$langを廃止する必要がある。

**Comment by nakatsuka-k** [comment]
@shigurenimo 
何が機能しない？
