### ISSUE TITLE
classNameではclsxを使用する

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#718]
## どのような問題がありますか？

クラスが重複する可能性があるので分離したりテンプレート文字列を使用したりしない。

![スクリーンショット 2024-09-21 14 36 30](https://github.com/user-attachments/assets/184a3b11-e496-45c2-a601-dcde8bb9b56b)

## どうすれば良いですか？

UIライブラリの提供する関数を使用する。

```
import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
```

これらを削除する。クラス名を返す関数を定義しない。

![スクリーンショット 2024-09-21 14 38 37](https://github.com/user-attachments/assets/d9f728b8-15a4-4cad-b467-bae320ee9013)

**Comment by nakatsuka-k** [comment]
@shigurenimo 
下記PRで修正した。
https://github.com/aipictors/aipictors/pull/753
