### ISSUE TITLE
複数の責務を持つ関数を削除する

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#720]
## どのような問題がありますか？

このように1つのモジュールに複数の責務を持たせると不具合に繋がる。

![スクリーンショット 2024-09-21 14 52 19](https://github.com/user-attachments/assets/c9391aa8-9615-4c4e-a982-8f87cb809589)

## どうすれば良いですか？

複数の責務を持つ大きなモジュールを作成しない。1つのモジュールは小さく単一の責務を持ち、それらを組み合わせてプログラムを構成する。

**Comment by nakatsuka-k** [comment]
マイページの該当の関数を削除した
https://github.com/aipictors/aipictors/pull/747

**Comment by nakatsuka-k** [comment]
@shigurenimo 
トップ画面、メニューの該当の関数を削除した
#754

**Comment by nakatsuka-k** [comment]
全画面のセンシティブフラグを削除した
https://github.com/aipictors/aipictors/pull/754
