### ISSUE TITLE
Error: parameter is required (check serviceDomain and apiKey)

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#723]
## どの機能に関する不具合ですか？

- [ ] 決済
- [ ] ログイン
- [ ] 投稿
- [ ] いいね
- [ ] リクエスト
- [ ] 多言語
- [ ] フィード
- [x] お知らせ
- [ ] お問い合わせ
- [ ] それ以外

## どのような不具合が発生しましたか？

環境変数の「VITE_MICRO_CMS_API_KEY」が空文字になっておりローカル環境でエラーが発生する。

## どのような操作をしましたか？

1. bun run dev
1. xxx
1. xxx

## どの端末で確認しましたか？

- [ ] iOS
- [ ] Android

## 許せないですか？

- [ ] 許せる
- [x] 許せない

**Comment by nakatsuka-k** [comment]
修正した。
https://github.com/aipictors/aipictors/commit/fb906d9b170a3974aa5547e57a26b15f41982751
