### ISSUE TITLE
ページのキャッシュコントロールを設定する

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#727]
## どのような問題がありますか？

キャッシュコントロールの設定されてないページでWorkerに到達してGraphQLサーバへのクエリが発生している。またLoaderの中で英語のページへのリダイレクトが発生しておりキャッシュコントロールが無効になっているページがある。キャッシュがヒットした場合はWorkerには到達しないか、日本語ページに英語ページがキャッシュされる。

## どうすれば良いですか？

適切なキャッシュコントロールを設定する。

**Comment by nakatsuka-k** [comment]
下記で全ページのキャッシュを追加した。
また、英語ページへのリダイレクトを無くした。
https://github.com/aipictors/aipictors/pull/766
