### ISSUE TITLE
Workerのサポートしない組み込みオブジェクトの参照を無くす

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#729]
Workerがサポートしていない組み込みオブジェクトが使用されている。

![スクリーンショット 2024-09-23 11 10 34](https://github.com/user-attachments/assets/f2a341ae-a200-4460-b13d-b3f7f9e4c8bf)

これにwindow.documentは含まれない。

https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers#%E3%83%AF%E3%83%BC%E3%82%AB%E3%83%BC%E3%81%A7%E4%BD%BF%E7%94%A8%E3%81%A7%E3%81%8D%E3%82%8B_api

![スクリーンショット 2024-09-23 11 11 55](https://github.com/user-attachments/assets/85e2c56d-99b2-4a01-b173-66b0200f26d0)

**Comment by nakatsuka-k** [comment]
コールバック以外の参照をなくして初回レンダリング時にエラーを出ないようにした。
