### ISSUE TITLE
AuthErrorなどのエラーはErrorクラスを継承する

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#730]
コードが難しく読めないのでクラスの継承に対しては関数の糖衣構文であるクラスを使用する。

```ts
export function AuthError(message?: string) {
  const error = new Error(message)
  error.name = "AuthError"
  Object.setPrototypeOf(error, AuthError.prototype)
  return error
}

AuthError.prototype = Object.create(Error.prototype)
AuthError.prototype.constructor = AuthError
```

- app/errors/auth-error.ts
- app/errors/params-error.ts

また、大文字から始まる関数を定義しない。

![スクリーンショット 2024-09-23 11 22 30](https://github.com/user-attachments/assets/7d52e54f-e11b-4a28-bed1-e02f1d4ceb34)

**Comment by nakatsuka-k** [comment]
Errorを継承する形に修正した。
https://github.com/aipictors/aipictors/pull/767
