### ISSUE TITLE
Cloudflare Fontsを使用してフォントの読み込みを高速化する

### ISSUE THREAD

**Issue by reiwa** [aipictors/aipictors#74]
## どのような問題がありますか？

フォントの読み込みが遅い場合がある？

## どうすれば良いですか？

Cloudflare Fontsというものがあるらしい。

**Comment by Katsuyuki-Karasawa** [comment]
- [Cloudflare Fonts をやってみる](https://zenn.dev/kameoncloud/articles/6603d068abb4ff)

**Comment by Katsuyuki-Karasawa** [comment]
ローカルに移したからclose
