### ISSUE TITLE
キャッシュするページを増やす

### ISSUE THREAD

**Issue by shigurenimo** [aipictors/aipictors#751]
## どのような問題がありますか？

関連: https://github.com/aipictors/aipictors/issues/727

キャッシュしていないページが多くWorkerに到達するので読み込みが遅い。

```ts
export async function loader(props: LoaderFunctionArgs) {
  return json(resp.data)
}
```

## どうすれば良いですか？

ここでは可能な限りページをキャッシュしてWorkerの呼び出しを防ぐ。キャッシュできない場合はその理由をコメントで関数に残しておきたい。

**Comment by nakatsuka-k** [comment]
@shigurenimo 
> キャッシュがヒットした場合はWorkerには到達しないか、日本語ページに英語ページがキャッシュされる。
Vary: Cookieを必ず設定し、キャッシュがCookieに応じて分岐するようにする。

**Comment by nakatsuka-k** [comment]
@shigurenimo 
トップ画面のキャッシュを修正した。
https://github.com/aipictors/aipictors/pull/752

**Comment by nakatsuka-k** [comment]
下記で全ページのキャッシュを追加した。
また、英語ページへのリダイレクトを無くした。
https://github.com/aipictors/aipictors/pull/766
