### ISSUE TITLE
pnpmへの移行

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [aipictors/aipictors#76]
## メリット
- 高速な依存関係のインストール
- プロジェクトのバージョンの一貫性
- CI/CDパフォーマンスの向上
- pnpmの強制
  - これにより、yarnやnpmなどではエラーになるので、環境を共通化できる
```json
{
    "scripts": {
        "preinstall": "npx only-allow pnpm"
    }
}
```

## 移行に伴い障害が発生する可能性のあるもの
- プロジェクトの互換性
  - とくにバックエンド寄り(GraphQLあたり)
- スクリプトの調整
  - Actions回り
- docsの修正

## 必要なテスト
- 単体テスト / 結合テスト
- 依存関係の一貫性の維持のチェック
- パフォーマンステスト
   - 移行後のビルドとテストのパフォーマンスの評価
   - npmとの比較

**Comment by reiwa** [comment]
Actionsが速くなるのか！？

**Comment by Katsuyuki-Karasawa** [comment]
CI全般は体感早いです
ただ、CIでぶん回すならBunでもいい気はするので、ローカルだと依存関係回りのイライラが解消する + 早くなるかもという感覚です

**Comment by reiwa** [comment]
完了？
